spring:
  application:
    name: weather.forecast
server:
  port: 8080
metno:
  client:
    base-url: https://api.met.no
    user-agent: weather-forecast-app/1.0 eneskantepe@gmail.com
    header-type: application/json
